name: Releasing in Github

on:
  push:
    branches: [ master ]
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Tag Message
      run: |
        echo ::set-output name=RELEASE_MESSAGE::git tag -l --format='%(contents:subject)' ${{ github.ref_name }}
    - name: Show Message
      run: |
        echo 'The message is: ${{ steps.vars.outputs.RELEASE_MESSAGE }}'
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: ${{ steps.vars.outputs.RELEASE_MESSAGE }}
